export enum OnboardingCheckpoint {
  INITIATED = 'INITIATED',
  EMAIL_OTP_SENT = 'EMAIL_OTP_SENT',
  EMAIL_CONFIRMED = 'EMAIL_CONFIRMED',
  MOBILE_VALIDATED = 'MOBILE_VALIDATED',
  MOBILE_OTP_SENT = 'MOBILE_OTP_SENT',
  MOBILE_CONFIRMED = 'MOBILE_CONFIRMED',
}
